
<form class="m-5">
  <div class="mb-3">
    <label for="Sample" class="form-label">Sample</label>
    <input type="text" class="form-control" id="Sample" aria-describedby="Input Sample">
    <div id="Sample" class="form-text">Enter Sample</div>
  </div>
  <div class="mb-3">
    <label for="Sea" class="form-label">Mer</label>
    <input type="text" class="form-control" id="Sea" name="sea">
    <div id="Sea" class="form-text">Mer où le sample a été trouvé</div>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>

</form>