<form class="m-5">

  <div class="mb-3">
    <label for="sample" class="form-label">Sample</label>
    <input type="text" class="form-control w-25" id="Sample" aria-describedby="Input Sample" name="sample">
  </div>
  <div class="mb-3">
    <label for="sea" class="form-label">Mer</label>
    <input type="text" class="form-control w-25" id="Sea" name="sea">
  </div>
  <div class="mb-3">
    <label for="date" class="form-label">Date</label>
    <input type="text" class="form-control w-25" id="Date" name="date">
  </div>
  <div class="mb-3">
    <label for="startTime" class="form-label">Start Time</label>
    <input type="text" class="form-control w-25" id="StartTime" name="startTime">
  </div>
  <div class="mb-3">
    <label for="startLatitude" class="form-label">Start Latitutde</label>
    <input type="text" class="form-control w-25" id="StartLatitude" name="startLatitude">
  </div>
  <div class="mb-3">
    <label for="startLongitude" class="form-label">Start Time</label>
    <input type="text" class="form-control w-25" id="StartLongitude" name="startLongitude">
  </div>
  <div class="mb-3">
    <label for="midLatitude" class="form-label">Mid Latitude</label>
    <input type="text" class="form-control w-25" id="MidLatitude" name="midLatitude">
  </div>
  <div class="mb-3">
    <label for="midLongitude" class="form-label">Mid Longitude</label>
    <input type="text" class="form-control w-25" id="MidLongitude" name="midLongitude">
  </div>
  <div class="mb-3">
    <label for="endLatitude" class="form-label">End Latitude</label>
    <input type="text" class="form-control w-25" id="EndLatitude" name="endLatitude">
  </div>
  <div class="mb-3">
    <label for="endLongitude" class="form-label">End Longitude</label>
    <input type="text" class="form-control w-25" id="EndLongitude" name="endLongitude">
  </div>
  <div class="mb-3">
    <label for="windForce" class="form-label">Wind Force</label>
    <input type="text" class="form-control w-25" id="WindForce" name="windForce">
  </div>
  <div class="mb-3">
    <label for="windSpeed" class="form-label">Wind Speed</label>
    <input type="text" class="form-control w-25" id="WindSpeed" name="windSpeed">
  </div>
  <div class="mb-3">
    <label for="windDirection" class="form-label">Wind Direction</label>
    <input type="text" class="form-control w-25" id="WindDirection" name="windDirection">
  </div>
  <div class="mb-3">
    <label for="seaState" class="form-label">Sea State</label>
    <input type="text" class="form-control w-25" id="SeaState" name="seaState">
  </div>
  <div class="mb-3">
    <label for="waterTemperature" class="form-label">Water Temperature</label>
    <input type="text" class="form-control w-25" id="WaterTemperature" name="waterTemperature">
  </div>
  <div class="mb-3">
    <label for="boatSpeed" class="form-label">Boat Speed</label>
    <input type="text" class="form-control w-25" id="BoatSpeed" name="boatSpeed">
  </div>
  <div class="mb-3">
    <label for="startFlowMeter" class="form-label">Start Flowmeter</label>
    <input type="text" class="form-control w-25" id="StartFlowMeter" name="startFlowMeter">
  </div>
  <div class="mb-3">
    <label for="endFlowMeter" class="form-label">End Flowmeter</label>
    <input type="text" class="form-control w-25" id="EndFlowMeter" name="endFlowMeter">
  </div>
  <div class="mb-3">
    <label for="filteredVolume" class="form-label">Filtered Volume</label>
    <input type="text" class="form-control w-25" id="FilteredVolume" name="filteredVolume">
  </div>
  <div class="mb-3">
    <label for="filteredDistance" class="form-label">Filtered Distance</label>
    <input type="text" class="form-control w-25" id="FilteredDistance" name="filteredDistance">
  </div>
  <div class="mb-3">
    <label for="filteredSurface" class="form-label">Filtered Surface (m)</label>
    <input type="text" class="form-control w-25" id="FilteredSurface" name="filteredSurface">
  </div>
  <div class="mb-3">
    <label for="filteredSurfaceKm" class="form-label">Filtered Surface (KM)</label>
    <input type="text" class="form-control w-25" id="FilteredSurfaceKm" name="filteredSurfaceKm">
  </div>
  <div class="mb-3">
    <label for="commentaires" class="form-label">Commentaires</label>
    <input type="text" class="form-control w-25" id="Commentaires" name="commentaires">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>

</form>