<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop</title>
    <base href="http://localhost/Back-end/shop/">
    <link rel="stylesheet" href="public/css/Base.css">
</head>

<body>
    <nav>
        <p>ADMINISTRATEUR</p>
        <a href="">Utilisateurs</a>
        <a href="">Produits</a>
    </nav>


    <main>
        <?php require_once $page; ?>
    </main>



</body>

</html>