<link rel="stylesheet" href="public/css/map.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
<div class="container-fluid">
    <h1 class="text-center m-4">Présentation de l'association</h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Adipisci dicta atque accusantium nostrum esse? Quasi recusandae, iure labore accusamus rem nisi maiores explicabo odit, magni eveniet quibusdam nemo at iusto!
    Tempore voluptatibus blanditiis delectus sunt explicabo fugit adipisci quia, deserunt laboriosam reprehenderit tenetur totam dolores in rerum, culpa error fuga maxime debitis eaque! Nobis quaerat corrupti enim ducimus nam hic?
    Assumenda earum officia omnis laboriosam! Quas laudantium ullam tenetur ipsum ad excepturi expedita ab officia sequi odio consequatur vitae odit, maxime est id reiciendis sed amet accusamus! Rerum, esse in?
    Ab iste odio accusamus labore enim assumenda fuga cumque hic quasi nobis optio minus rem, vel maxime possimus quos porro dignissimos magni a? Tempora quaerat accusantium repudiandae aspernatur quibusdam ipsam?
    Ipsam possimus aut expedita. Delectus voluptate ducimus vel dolore, sed nam aliquam. Alias dolores explicabo sunt placeat tempore ducimus quae natus ipsum repellat veniam? Quibusdam at autem incidunt minima tempora!
    Totam, ipsa incidunt deleniti ab nemo odit odio, laboriosam dignissimos numquam reprehenderit, error saepe illo laudantium itaque commodi ipsam! Animi eos maxime sit similique omnis aperiam sed porro est ipsum.
    Exercitationem iste alias animi labore? Est, natus dicta. Rerum voluptatibus nostrum quos nemo repellendus molestiae eaque explicabo dolorum fugiat recusandae libero dolores optio non ut ex aliquid excepturi, inventore amet!
    Soluta fugit eaque beatae ullam? Sit, debitis necessitatibus delectus inventore dolorem sapiente totam odit magni repudiandae natus qui optio saepe perferendis aperiam nisi. Mollitia libero facilis non, temporibus sequi iusto.
    Soluta nobis error alias eum possimus facere vero repellat perferendis? Vel a, reprehenderit, ut quia consequatur eius quisquam earum eos amet, maxime perferendis molestias magnam quasi voluptas excepturi atque laborum?
    Recusandae neque, eveniet consequuntur maxime, animi reiciendis assumenda voluptatem ratione nemo vel ducimus! Saepe cum nobis unde deserunt aspernatur impedit inventore, repudiandae odio sint nemo praesentium explicabo ducimus sunt consequatur.</p></div>
    <div id="map" class="rounded-1 m-5" ;></div>

<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
<script src="public/javascript/map.js"></script>