<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>


  <form class="m-5" method="POST" action="http://localhost/Hackaton/expedition-med/Users/loginPost">
    <div class="mb-3">
      <label for="Email" class="form-label">Adresse Email</label>
      <input type="email" class="form-control" id="Email" name="email" aria-describedby="input your Email Adress">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
      <label for="Password" class="form-label">Mot de Passe</label>
      <input type="password" class="form-control" id="Password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Se connecter</button>


  </form>
</body>

</html>